### ISSUE TITLE
HTTPError: 500 Server Error: Internal Server Error

### ISSUE THREAD

**Issue by denistribouillois** [angus-ai/angus-sdk-python#5]
Hello, I'm trying to use Angus SDk, but I got an HTTP Error 500.

I tried the "Hello World" example (with face_detection, gaze_analysis and others) and I got the following error:

"Traceback (most recent call last):
  File "test.py", line 7, in <module>
    job = service.process({'image': open('.\denis.jpg')})
  File "C:\Python27\lib\site-packages\angus\rest.py", line 185, in process
    resource_type=Job)
  File "C:\Python27\lib\site-packages\angus\rest.py", line 118, in create
    r.raise_for_status()
  File "C:\Python27\lib\site-packages\requests\models.py", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error"

If I try the "Hello World" example with dummy I don't have any error though. So it seems like I'm connecting correctly to the servers.
Could it be client side (firewall, libs...) or server side ?
I'm using python and windows 10.
Best regards, Denis.

**Comment by ggate** [comment]
Hi,

First, so sorry for getting back to you so late.
This comes from different default behavior of the open() function on Windows vs Linux/Mac.

The file needs to be opened in binary mode. Adding `'rb'` to `open()` seems to solve the problem:
`job = service.process({'image': open('.\denis.jpg', 'rb')})`

We've just updated our doc accordingly. 
Let me know if it is ok now.

Best regards,

Gwenn

**Comment by AnuEli** [comment]
Hi,
I faced the same problem.
Unfortunately, that does not solve the problem. I get the same error in Linux and also in Windows when opening file in binary mode.
Best regards,
Anu

**Comment by denistribouillois** [comment]
Hi Gwenn,
Thanks for the update, I tried again the exact same test that I was running when I got the issue and had a different error: 

{u'url': u'https://gate.angus.ai/services/gaze_analysis/1/jobs/a729c6bc-c823-11e6-9602-0242ac110002', u'status': 201, u'uuid': u'a729c6bc-c823-11e6-9602-0242ac110002', u'Error': u'Input does not appear to be valid, please check that you send well formated png or jpg images.'}

So it seems that the connection works now without any problem, but still could not open the image without 'rb' mode.
I then added 'rb' to open() like you suggested and it worked like a charm!

Tried with Windows 10, not tested with Linux.
(I though changed my office and connexion settings since last time I tried)

Anyway it's working for me now, thank you again.
Denis
